/**
 * BadConsequence.java
 * @author Jose Carlos Entrena
 * @author Mario Román 
 * @author Óscar Bermúdez
 */

package GUI;
import Game.BadConsequence;


public class BadConsequenceView extends javax.swing.JPanel {
    BadConsequence badConsequenceModel; 
    
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    public void setBadConsequence(BadConsequence bad){
        badConsequenceModel = bad; 
        badConsequenceTextLabel.setText(badConsequenceModel.getText());
        repaint();    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        badConsequenceLabel = new javax.swing.JLabel();
        badConsequenceTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        badConsequenceLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        badConsequenceLabel.setText("Mal rollo:");

        badConsequenceTextLabel.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        badConsequenceTextLabel.setText("<html> Texto asociado a la BadConsequence <br> Segunda líena de texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(badConsequenceLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(badConsequenceTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(badConsequenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badConsequenceTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel badConsequenceLabel;
    private javax.swing.JLabel badConsequenceTextLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
