package GUI;
import Game.CultistPlayer;
import Game.Treasure;
import Game.Player;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author José Carlos Entrena
 * @author Mario Román
 * @author Óscar Bermúdez
 */
public class PlayerView extends javax.swing.JPanel {
    Player playerModel; 

    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }

    public void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> treasureList) {
        // Se eliminan los elementos y se añaden los nuevos. 
        aPanel.removeAll(); 
        for (Treasure t : treasureList){
            TreasureView treasureView = new TreasureView(); 
            treasureView.setTreasure(t); 
            treasureView.setVisible(true);
            aPanel.add(treasureView); 
        }
        
        aPanel.repaint(); 
        aPanel.revalidate(); 
    }
    
    public void setPlayer(Player p){
        playerModel = p; 
        nameLabel.setText(playerModel.getName());
        levelLabel.setText(Integer.toString(playerModel.getLevel()));
        combatLevelLabel.setText(Integer.toString(playerModel.getCombatLevel()));
        // Si es un sectario actualizamos su carta de sectario. 
        if (playerModel.getClass() == CultistPlayer.class)
            cultistView.setCultist(((CultistPlayer) playerModel).getCultistCard());
        
        fillTreasurePanel(visibleTreasuresPanel, playerModel.getVisibleTreasures());
        fillTreasurePanel(hiddenTreasuresPanel, playerModel.getHiddenTreasures());
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        visibleTreasuresPanel = new javax.swing.JPanel();
        hiddenTreasuresPanel = new javax.swing.JPanel();
        nivelCombate = new javax.swing.JLabel();
        combatLevelLabel = new javax.swing.JLabel();
        cultistView = new GUI.CultistView();
        buyLevelsButton = new javax.swing.JButton();
        makeTreasuresVisibleButton = new javax.swing.JButton();
        discardTreasuresButton = new javax.swing.JButton();

        nameLabel.setText("Nombre");

        nivel.setText("Nivel");

        levelLabel.setText("Nº nivel");

        nivelCombate.setText("Nivel de Combate");

        combatLevelLabel.setText("CombatLevel");

        buyLevelsButton.setText("Comprar Niveles");

        makeTreasuresVisibleButton.setText("Hacer Tesoros Visibles");

        discardTreasuresButton.setText("Eliminar Tesoros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyLevelsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(makeTreasuresVisibleButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nivelCombate)
                                .addGap(30, 30, 30)
                                .addComponent(combatLevelLabel))
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discardTreasuresButton)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nivel)
                        .addGap(18, 18, 18)
                        .addComponent(levelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cultistView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nameLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivel)
                            .addComponent(levelLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cultistView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelCombate)
                    .addComponent(combatLevelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buyLevelsButton)
                        .addComponent(makeTreasuresVisibleButton)
                        .addComponent(discardTreasuresButton)))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyLevelsButton;
    private javax.swing.JLabel combatLevelLabel;
    private GUI.CultistView cultistView;
    private javax.swing.JButton discardTreasuresButton;
    private javax.swing.JPanel hiddenTreasuresPanel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton makeTreasuresVisibleButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nivelCombate;
    private javax.swing.JPanel visibleTreasuresPanel;
    // End of variables declaration//GEN-END:variables
}
