/**
 * PrizeView.java
 * @author Jose Carlos Entrena
 * @author Mario Román 
 * @author Óscar Bermúdez
 */
package GUI;
import Game.Prize;

public class PrizeView extends javax.swing.JPanel {
    Prize prizeModel;
    
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }
    
    public void setPrize(Prize p){
        prizeModel = p; 
        treasuresLabel.setText(Integer.toString(prizeModel.getTreasures()));
        levelsLabel.setText(Integer.toString(prizeModel.getLevels()));
        repaint();    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prizeTextLabel = new javax.swing.JLabel();
        treasuresTextLabel = new javax.swing.JLabel();
        levelsTextLabel = new javax.swing.JLabel();
        treasuresLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();

        prizeTextLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        prizeTextLabel.setText("Prize:");

        treasuresTextLabel.setText("Treasures:");

        levelsTextLabel.setText("Levels:");

        treasuresLabel.setText("0");

        levelsLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prizeTextLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(treasuresTextLabel)
                            .addComponent(levelsTextLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(treasuresLabel)
                            .addComponent(levelsLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prizeTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treasuresTextLabel)
                    .addComponent(treasuresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelsTextLabel)
                    .addComponent(levelsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel levelsTextLabel;
    private javax.swing.JLabel prizeTextLabel;
    private javax.swing.JLabel treasuresLabel;
    private javax.swing.JLabel treasuresTextLabel;
    // End of variables declaration//GEN-END:variables
}
